version: '3.8'

services:
  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: precatorios-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      
      # External MongoDB Configuration
      MONGODB_URI: ${MONGODB_URI}
      
      # Application Configuration
      NEXTAUTH_URL: https://${DOMAIN}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      
      # Evolution API Configuration
      EVOLUTION_API_URL: ${EVOLUTION_API_URL}
      EVOLUTION_API_KEY: ${EVOLUTION_API_KEY}
      
      # MinIO Configuration (external service)
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PORT: ${MINIO_PORT:-443}
      MINIO_USE_SSL: ${MINIO_USE_SSL:-true}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME:-precatorios-files}
      
      # OpenAI Configuration (optional)
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    networks:
      - traefik
    volumes:
      - ./uploads:/app/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.precatorios.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.precatorios.tls=true"
      - "traefik.http.routers.precatorios.tls.certresolver=letsencrypt"
      - "traefik.http.services.precatorios.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true